language: node_js
node_js:
- '6'
- '8'
cache:
  directories:
  - node_modules

script:
  - npm run build
  - npm test

after_script: npm run coverage

deploy:
  node_js: lts/*
  skip_cleanup: true
  provider: script
  script:
    - npx semantic-release
  on:
    branch: master
